require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'

# Metrics/LineLength:
#   Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
  - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'app/models/spotlight/resource.rb'
    - 'lib/generators/spotlight/**/*' # Generators tend to have longer class lengths due to their lengthy public API
